const THROW_EXCEPTION = {
  UNKNOWN_TRANSACTION: 'Something went wrong. <br /> Please try again!',
  ONCHAIN_TIMEOUT: 'Network too busy. <br /> Please try again!',
  USER_REJECTED_THE_REQUEST: 'User rejected the request.',
};

export { THROW_EXCEPTION };
